import: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false

formatter:
  page_width: 120