name: core_video_player
description: A customizable video player widget for Flutter.
version: 1.1.0
homepage: https://github.com/jbarretojr/core-video-player

environment:
  sdk: ^3.12.0

dependencies:
  async: ^2.13.0
  audio_video_progress_bar: ^2.0.3
  connectivity_plus: ^7.3.0
  floating: ^6.0.0
  flutter:
    sdk: flutter
  http: ^1.5.0
  keep_screen_on: ^6.0.0
  platform: ^3.1.6
  video_player: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.3.0
